### PR TITLE
updpkg 0.5.13

### LINKED ISSUE #1: ModuleNotFoundError: `std_msgs` at roslaunch
Launching throws a `ModuleNotFoundError: No module named 'std_msgs'`. 
```
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/roslaunch", line 34, in <module>
    import roslaunch
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/__init__.py", line 62, in <module>
    from .scriptapi import ROSLaunch
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/scriptapi.py", line 42, in <module>
    import roslaunch.parent
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/parent.py", line 54, in <module>
    import roslaunch.server
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/server.py", line 79, in <module>
    from rosgraph_msgs.msg import Log
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/__init__.py", line 2, in <module>
    from ._Log import *
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/_Log.py", line 8, in <module>
    import std_msgs.msg
ModuleNotFoundError: No module named 'std_msgs'
```
Updating to 0.5.13 did indeed solve it as claimed by @avisy in the [AUR page](https://aur.archlinux.org/packages/ros-melodic-std-msgs/).
> update to ros-melodic-std-msgs 0.5.13 can solve it.

### PR DESCRIPTION
**Pull request by acxz**
resolves #1

### CODE REVIEW

**Comment by jwhendy** [comment]
Looks fine, and we should update anyway, but I wanted to comment that I do not have the issues from #1 on 0.5.12. I think there's something else going on, and I hesitate to use an upgrade to magically fix it, especially if we haven't reproduced it/nailed down the cause.

Still, go for the update as there's no reason not to.

**Comment by bionade24** [comment]
What about the `arch=()` array? Is any really correct?

**Comment by acxz** [comment]
I don't think so, this package generates python, javascript, lisp, and C++ code (headers only) for the `.msg` types. It doesn't do any compilation of C++ code itself.

**Comment by bionade24** [comment]
I'll test

**Comment by bionade24** [comment]
You're right.  Wasn't sure, tested it.

**Pull request merged**
